name: ðŸŽ¨ Format Code

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop

permissions:
    contents: read

jobs:
    format-dotnet:
        name: Format .NET Files
        runs-on: ubuntu-latest

        steps:
            - name: ðŸ“‚ Checkout Code
              uses: actions/checkout@v6

            - name: ðŸ”§ Setup .NET
              uses: grovegs/actions/.github/actions/setup-dotnet@v1.0.10
              with:
                  global-json-file: sandbox/ConsoleApplication/global.json

            - name: ðŸŽ¨ Format .NET ConsoleApplication
              uses: grovegs/actions/.github/actions/format-dotnet@v1.0.10
              with:
                  project: sandbox/ConsoleApplication

            - name: ðŸŽ¨ Format .NET GodotApplication
              uses: grovegs/actions/.github/actions/format-dotnet@v1.0.10
              with:
                  project: sandbox/GodotApplication

    format-files:
        name: Format Files
        runs-on: ubuntu-latest

        steps:
            - name: ðŸ“‚ Checkout Code
              uses: actions/checkout@v6

            - name: ðŸŽ¨ Format YAML Files
              uses: grovegs/actions/.github/actions/format-files@v1.0.10
              with:
                  files: "**/*.{yml,yaml}"
                  ignore-path: ".gitignore"

            - name: ðŸŽ¨ Format JSON Files
              uses: grovegs/actions/.github/actions/format-files@v1.0.10
              with:
                  files: "**/*.json"
                  ignore-path: ".gitignore"

            - name: ðŸŽ¨ Format Markdown Files
              uses: grovegs/actions/.github/actions/format-files@v1.0.10
              with:
                  files: "**/*.md"
                  ignore-path: ".gitignore"
