name: ğŸš€ Release Godot Android

on:
  workflow_call:
    inputs:
      project:
        description: The relative path to the Godot project directory containing the `project.godot` file.
        required: true
        type: string
      environment:
        description: The build environment (e.g., Development, Production).
        required: true
        type: string
      version:
        description: The version number for the build (e.g., 1.0.0).
        required: true
        type: string
      format:
        description: The Android build format. Supported values are `apk` or `aab`.
        required: true
        type: string
      release-notes:
        description: Release notes for the update. Provide a brief description of changes in the release.
        required: false
        default: ""
        type: string
      firebase-tester-groups:
        description: Comma-separated list of Firebase tester groups to receive the build. Used for Firebase App Distribution.
        required: false
        default: ""
        type: string
    secrets:
      keystore:
        description: Base64-encoded content of the Android keystore for signing the build.
        required: true
      keystore-user:
        description: Username for the Android keystore.
        required: true
      keystore-password:
        description: Password for the Android keystore.
        required: true
      firebase-app-id:
        description: Firebase app ID for uploading builds to Firebase App Distribution.
        required: false
      firebase-credentials:
        description: Firebase service account credentials for authentication.
        required: false

jobs:
  release_godot_android:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v4

      - name: â˜• Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: ğŸ› ï¸ Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: platform-tools build-tools;34.0.0 platforms;android-34 cmake;3.10.2.4988404 ndk;23.2.8568313

      - name: ğŸ® Setup Godot
        uses: grovegs/actions/.github/actions/setup-godot@refactor/reusable-workflow
        with:
          global-json-file: ${{ inputs.project }}/global.json
          target-platforms: Android
          cached: true

      - name: ğŸ” Get Project Name
        id: get_project_name
        run: echo "project_name=$(basename ${{ inputs.project }})" >> $GITHUB_OUTPUT

      - name: ğŸ—ï¸ Build Project
        id: build_project
        uses: grovegs/actions/.github/actions/build-godot@refactor/reusable-workflow
        with:
          project: ${{ inputs.project }}
          global-json-file: ${{ inputs.project }}/global.json
          version: ${{ inputs.version }}
          platform: Android
          preset: Android ${{ inputs.environment }}
          configuration: Debug
          file-name: ${{ steps.get_project_name.outputs.project_name }}
          android-keystore: ${{ secrets.keystore }}
          android-keystore-user: ${{ secrets.keystore-user }}
          android-keystore-password: ${{ secrets.keystore-password }}
          android-format: ${{ inputs.format }}

      - name: ğŸ“¤ Publish to Firebase
        if: ${{ inputs.environment == 'Development' }}
        uses: grovegs/actions/.github/actions/publish-firebase@refactor/reusable-workflow
        with:
          file: ${{ steps.build_project.outputs.file }}
          app-id: ${{ secrets.firebase-app-id }}
          credentials: ${{ secrets.firebase-credentials }}
          release-notes: ${{ inputs.release-notes }}
          tester-groups: ${{ inputs.firebase-tester-groups }}
